### ISSUE TITLE
Surprising behavior when passing an invalid type

### ISSUE THREAD

**Issue by axelson** [emadalam/mahaul#1]
Hi there! :wave:
First off, thanks for making this library! I'm excited to see an alternative approach to using environment variables in Elixir :tada:

I didn't read the docs thoroughly the first time I started using this and I set up my env like so:

```
defmodule Dash.Env do
  use Mahaul,
    TRELLO_API_KEY: [type: :string],
    TRELLO_API_TOKEN: [type: :string],
    PIRATE_WEATHER_API_KEY: [type: :string]
```

This results in `Dash.Env.validate()` giving the following error even when those environment variables are set:
```
14:54:01.654 [warning] Elixir.Mahaul.Helpers: missing or invalid environment variables.
TRELLO_API_KEY
TRELLO_API_TOKEN
PIRATE_WEATHER_API_KEY

{:error, "TRELLO_API_KEY\nTRELLO_API_TOKEN\nPIRATE_WEATHER_API_KEY"}
```

After reading the docs I found that the correct type is `:str`, not `:string`, while I do have a slight preference for both of them working that's not my main point here. My main point is that I think that either at compile-time or runtime when calling `Dash.Env.validate()` I should get an error that the `type` was not recognized.

**Comment by emadalam** [comment]
Hi @axelson! Thanks for trying out the library 🙌 

You are right, the error handling and DX could be improved. Since the library boasts compile time validations wherever possible, I believe a better DX would be to identify invalid options at compile time itself and raise argument errors. The calls to `validate/1` and `validate!/1` are meant to validate the environment variables before application boot from inside `config/runtime.exs` and the invalid usage of the library itself should have been caught way earlier than that.

I did update the code in PR #2  to have a working validation that looks something like below.

![Screenshot 2023-02-27 at 12 21 37](https://user-images.githubusercontent.com/1067689/221553439-e79beb8b-35e0-4c95-a1f2-5a4190bcde96.png)

![Screenshot 2023-02-27 at 12 22 02](https://user-images.githubusercontent.com/1067689/221553446-b61b3a2a-f3a5-42ad-8d2b-19aac595ab85.png)

![Screenshot 2023-02-27 at 12 22 40](https://user-images.githubusercontent.com/1067689/221553448-c7c90c32-4eb8-4634-9a6f-e51e0bbb9434.png)

![Screenshot 2023-02-27 at 12 23 01](https://user-images.githubusercontent.com/1067689/221553452-5481c162-4944-4734-9ee5-4577c759ff8c.png)

![Screenshot 2023-02-27 at 12 23 31](https://user-images.githubusercontent.com/1067689/221553453-2aea64e1-dddb-4098-8464-bb0ac5a26f6a.png)

![Screenshot 2023-02-27 at 12 28 27](https://user-images.githubusercontent.com/1067689/221553457-526b0d60-7838-4ba0-a4ef-9229917bbc04.png)

What do you think about this? I can make a release to support this kind of compile time validations of all supported options. Do let me know if you would like to test this out before I make an official release 🙏

**Comment by axelson** [comment]
Thanks! That's a great improvement :tada:

One suggestion: can you add more context to the error message itself? If a user is defining many environment variables then it would be helpful to know which variable is the one that is associated with the error. You can tell via the `got: :string` but knowing the environment variable name directly would help the developer find the incorrect definition more quickly.

**Comment by emadalam** [comment]
@axelson excellent suggestion, added it to the implementation ✅ 

![Screenshot 2023-02-27 at 19 24 08](https://user-images.githubusercontent.com/1067689/221651296-0457f4c0-02cd-4af0-819b-efe4d06c5264.png)

![Screenshot 2023-02-27 at 19 23 34](https://user-images.githubusercontent.com/1067689/221651293-f85bd8e6-ca3d-4cd1-a4ca-b6285f5084e7.png)

Let me know if this covers all the use case. I'd make a release then 🙌

**Comment by axelson** [comment]
Looks good to me! Thanks!
